### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by abertranb** [JuezUN/OnlinePythonTutor#13]
Hi! thanks for the project I have 2 questions

1) When I launch the aplication always shows Python 3.3 but I see some commits that has been upgraded to 3.6. Is an interface issue?
2) You are using v3 instead V5-unity, also there is an upgrade to v6 like https://github.com/diogo55/OnlinePythonTutor

Thanks!!!

**Comment by crdgonzalezca** [comment]
Hi @abertranb, thanks for reaching out. 

> 1. When I launch the aplication always shows Python 3.3 but I see some commits that has been upgraded to 3.6. Is an interface issue?

For your first question, we only use this service in the embedded way, thus we have indeed updated this frontend part, but only for the embedded html. The other pages may still show python 3.3, even though, the python version in the docker container is higher. So to answer the question, yes, this is just a frontend issue. 

> 2. You are using v3 instead V5-unity, also there is an upgrade to v6 like https://github.com/diogo55/OnlinePythonTutor

Thanks, we had not noticed the `v6` before. We have no plans right now to upgrade to version `v5` though, but I'm gonna check this out and see whether we upgrade this or not, because there are several changes we might need to do.

Hope this answers your questions and thank you!
